import './globals.css'
import { Inter } from 'next/font/google'
import { ApolloWrapper } from './apolloClient/apollo-wrapper'
import { Navbar } from '@/component/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }:{children: React.ReactNode}) {
  return (
    <html lang="en">
      <head>
      
      </head>
      <body>
        {/* <Navbar/> */}
        <ApolloWrapper>{children}</ApolloWrapper>
      </body>
    </html>
  );
}
